financial_analysis:
  description: >
    Conduct a thorough analysis of {company_stock}'s stock financial health and market performance. This includes examining key financial metrics such as
    P/E ratio, EPS growth, revenue trends, and debt-to-equity ratio. Also, analyze the stock's performance in comparison 
    to its industry peers and overall market trends.

  expected_output: >
    The final report must expand on the summary provided but now 
    including a clear assessment of the stock's financial standing, its strengths and weaknesses, 
    and how it fares against its competitors in the current market scenario.
    Make sure to use the most recent data possible.



recommend:
  description: >
    Review and synthesize the analyses provided by the
    Financial Analyst and the Research Analyst.
    Combine these insights to form a comprehensive
    investment recommendation. You MUST Consider all aspects, including financial
    health, market sentiment, and qualitative data from
    EDGAR filings. 
    
    Make sure to include a section that shows insider 
    trading activity, and upcoming events like earnings.

  expected_output: > 
    Your final answer MUST be a recommendation for your customer. It should be a full super detailed report, providing a 
    clear investment stance and strategy with supporting evidence.
    Make it pretty and well formatted for your customer.
