stock_query:
  description: >
    Conduct a thorough analysis of {company_stock}股票代码，sh或sz.+6位数字代码，或者指数代码，如：sh.601398。sh：上海；sz：深圳
  expected_output: >
    中文输出工具获得的信息

financial_analysis:
  description: >
    Conduct a thorough analysis of {company_stock}'s stock financial health and market performance. This includes examining key financial metrics such as
    P/E ratio, EPS growth, revenue trends, and debt-to-equity ratio. Also, analyze the stock's performance in comparison 
    to its industry peers and overall market trends.

  expected_output: >
    中文输出,The final report must expand on the summary provided but now 
    including a clear assessment of the stock's financial standing, its strengths and weaknesses, 
    and how it fares against its competitors in the current market scenario.
    Make sure to use the most recent data possible.

ben-graham-analyst:
  description: >
    Conduct a thorough analysis of {company_stock}'s stock,
    1. Insist on a margin of safety by buying below intrinsic value (e.g., using Graham Number, net-net).
    2. Emphasize the company's financial strength (low leverage, ample current assets).
    3. Prefer stable earnings over multiple years.
    4. Consider dividend record for extra safety.
    5. Avoid speculative or high-growth assumptions; focus on proven metrics.

  expected_output: >
    中文输出
    1. Explaining the key valuation metrics that influenced your decision the most (Graham Number, NCAV, P/E, etc.)
    2. Highlighting the specific financial strength indicators (current ratio, debt levels, etc.)
    3. Referencing the stability or instability of earnings over time
    4. Providing quantitative evidence with precise numbers
    5. Comparing current metrics to Graham's specific thresholds (e.g., "Current ratio of 2.5 exceeds Graham's minimum of 2.0")
    6. Using Benjamin Graham's conservative, analytical voice and style in your explanation
    For example, if bullish: "The stock trades at a 35% discount to net current asset value, providing an ample margin of safety. The current ratio of 2.5 and debt-to-equity of 0.3 indicate strong financial position..."
    For example, if bearish: "Despite consistent earnings, the current price of $50 exceeds our calculated Graham Number of $35, offering no margin of safety. Additionally, the current ratio of only 1.2 falls below Graham's preferred 2.0 threshold..."
    Return a rational recommendation: bullish, bearish, or neutral, with a confidence level (0-100) and thorough reasoning

recommend:
  description: >
    Review and synthesize the analyses provided by the
    Financial Analyst and the Research Analyst.
    Combine these insights to form a comprehensive
    investment recommendation. You MUST Consider all aspects, including financial
    health, market sentiment, and qualitative data from
    EDGAR filings. 
    
    Make sure to include a section that shows insider 
    trading activity, and upcoming events like earnings.

  expected_output: > 
    中文输出,Your final answer MUST be a recommendation for your customer. It should be a full super detailed report, providing a 
    clear investment stance and strategy with supporting evidence.
    Make it pretty and well formatted for your customer.
