stock_query:
  description: >
    Conduct a thorough analysis of {company_stock}股票代码，sh或sz.+6位数字代码，或者指数代码，如：sh.601398。sh：上海；sz：深圳
  expected_output: >
    中文输出工具获得的信息

financial_analysis:
  description: >
    Conduct a thorough analysis of {company_stock}'s stock financial health and market performance. This includes examining key financial metrics such as
    P/E ratio, EPS growth, revenue trends, and debt-to-equity ratio. Also, analyze the stock's performance in comparison 
    to its industry peers and overall market trends.

  expected_output: >
    中文输出,The final report must expand on the summary provided but now 
    including a clear assessment of the stock's financial standing, its strengths and weaknesses, 
    and how it fares against its competitors in the current market scenario.
    Make sure to use the most recent data possible.

ben-graham-analyst:
  description: >
    Conduct a thorough analysis of {company_stock}'s stock,
    1. Insist on a margin of safety by buying below intrinsic value (e.g., using Graham Number, net-net).
    2. Emphasize the company's financial strength (low leverage, ample current assets).
    3. Prefer stable earnings over multiple years.
    4. Consider dividend record for extra safety.
    5. Avoid speculative or high-growth assumptions; focus on proven metrics.

  expected_output: >
    中文输出
    1. Explaining the key valuation metrics that influenced your decision the most (Graham Number, NCAV, P/E, etc.)
    2. Highlighting the specific financial strength indicators (current ratio, debt levels, etc.)
    3. Referencing the stability or instability of earnings over time
    4. Providing quantitative evidence with precise numbers
    5. Comparing current metrics to Graham's specific thresholds (e.g., "Current ratio of 2.5 exceeds Graham's minimum of 2.0")
    6. Using Benjamin Graham's conservative, analytical voice and style in your explanation
    For example, if bullish: "The stock trades at a 35% discount to net current asset value, providing an ample margin of safety. The current ratio of 2.5 and debt-to-equity of 0.3 indicate strong financial position..."
    For example, if bearish: "Despite consistent earnings, the current price of $50 exceeds our calculated Graham Number of $35, offering no margin of safety. Additionally, the current ratio of only 1.2 falls below Graham's preferred 2.0 threshold..."
    Return a rational recommendation: bullish, bearish, or neutral, with a confidence level (0-100) and thorough reasoning

warren_buffett_analyst:
  description: >
    Conduct a thorough analysis of {company_stock}'s stock,
    1. Circle of Competence: "Risk comes from not knowing what you're doing." Only invest in businesses I thoroughly understand.
    2. Economic Moats: Seek companies with durable competitive advantages - pricing power, brand strength, scale advantages, switching costs.
    3. Quality Management: Look for honest, competent managers who think like owners and allocate capital wisely.
    4. Financial Fortress: Prefer companies with strong balance sheets, consistent earnings, and minimal debt.
    5. Intrinsic Value & Margin of Safety: Pay significantly less than what the business is worth - "Price is what you pay, value is what you get."
    6. Long-term Perspective: "Our favorite holding period is forever." Look for businesses that will prosper for decades.
    7. Pricing Power: The best businesses can raise prices without losing customers.
  expected_output: >
    中文输出,
    MY INVESTMENT CRITERIA HIERARCHY:
    First: Circle of Competence - If I don't understand the business model or industry dynamics, I don't invest, regardless of potential returns.
    Second: Business Quality - Does it have a moat? Will it still be thriving in 20 years?
    Third: Management - Do they act in shareholders' interests? Smart capital allocation?
    Fourth: Financial Strength - Consistent earnings, low debt, strong returns on capital?
    Fifth: Valuation - Am I paying a reasonable price for this wonderful business?

    MY LANGUAGE & STYLE:
    - Use folksy wisdom and simple analogies ("It's like...")
    - Reference specific past investments when relevant (Coca-Cola, Apple, GEICO, See's Candies, etc.)
    - Quote my own sayings when appropriate
    - Be candid about what I don't understand
    - Show patience - most opportunities don't meet my criteria
    - Express genuine enthusiasm for truly exceptional businesses
    - Be skeptical of complexity and Wall Street jargon

    CONFIDENCE LEVELS:
    - 90-100%: Exceptional business within my circle, trading at attractive price
    - 70-89%: Good business with decent moat, fair valuation
    - 50-69%: Mixed signals, would need more information or better price
    - 30-49%: Outside my expertise or concerning fundamentals
    - 10-29%: Poor business or significantly overvalued

    Remember: I'd rather own a wonderful business at a fair price than a fair business at a wonderful price. And when in doubt, the answer is usually "no" - there's no penalty for missed opportunities, only for permanent capital loss. 

recommend:
  description: >
    Review and synthesize the analyses provided by the
    Financial Analyst and the Research Analyst.
    Combine these insights to form a comprehensive
    investment recommendation. You MUST Consider all aspects, including financial
    health, market sentiment, and qualitative data from
    EDGAR filings. 
    
    Make sure to include a section that shows insider 
    trading activity, and upcoming events like earnings.

  expected_output: > 
    中文输出,Your final answer MUST be a recommendation for your customer. It should be a full super detailed report, providing a 
    clear investment stance and strategy with supporting evidence.
    Make it pretty and well formatted for your customer.
